services:
  - type: web
    name: sage-love-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        fromDatabase: false  # Set this in Render dashboard environment variables
      - key: ALLOWED_ORIGIN
        value: "*"
      - key: DAILY_TOKEN_LIMIT
        value: "50000"
      - key: MONTHLY_REQUEST_LIMIT
        value: "1000"