export default {
  "appName": "Sage's Love (AI)",
  "appSubtitle": "Speak with the Sage and find your heart's guide.",
  "welcomeMessage": "Welcome, seeker of truth.",
  "chatPlaceholder": "Enter what you wish to ask the Sage...",
  "chatCharacterCountLabel": "Character count: {{current}} of {{max}}",
  "chatVoiceListening": "Listening...",
  "voiceMicPermissionDenied": "Microphone access was denied. Please enable microphone permission in your browser settings.",
  "voiceMicPermissionRequired": "Microphone access is required",
  "voiceListening": "Listening - click to stop",
  "voiceStart": "Start voice input",
  "voiceStop": "Stop voice input",
  "translationQualityLabel": "Translation quality:",
  "translationReportTooltip": "Report a translation quality issue",
  "translationReportButton": "Report quality",
  "termsImportantLimitsTitle": "Important Limitations",
  "termsImportantLimit1": "Responses from the AI are not guidance from an actual sage.",
  "termsImportantLimit2": "Cannot be used as a substitute for professional medical or legal advice.",
  "termsImportantLimit3": "Users under 18 require parental consent.",
  "termsImportantLimit4": "Inappropriate use may be restricted.",
  "termsProhibitedTitle": "Prohibited Conduct",
  "termsProhibitedText": "Violations of law, harassment of others, posting inappropriate content, unauthorized use of the service, and commercial use are all prohibited.",
  "termsEmergencyTitle": "Emergencies",
  "termsEmergencyText": "In the event of serious problems or emergencies, please do not rely on this service and consult a qualified professional or emergency service immediately.",
  "termsLastUpdated": "Last updated: January 2025",
  "phone": "Phone",
  "web": "Web",
  "hours": "Hours",
  "free": "Free",
  "showMore": "Show more",
  "showLess": "Show less",
  "understood": "I understand",
  "crisis": {
    "title": "Important Notice",
    "youAreNotAlone": "You are not alone",
    "helpAvailable": "Your feelings matter. Professionals are ready to support you. Asking for help is a sign of strength.",
    "aiLimitation": "AI has its limits. For serious mental health concerns, please reach out to the professional organizations listed below right away.",
    "emergencyResources": "Resources available right now",
    "importantNote": "Important note",
    "emergencyNote": "If your life is in danger, please contact emergency services immediately (US: 911, Japan: 119, etc.).",
    "footer": "Your life is precious. Please do not hesitate to ask for help.",
    "severity": {
      "critical": "Emergency",
      "high": "Urgent",
      "medium": "Caution",
      "low": "Mild"
    }
  },
  "sendButton": "Send",
  "sendingButton": "Sending...",
  "stopGeneratingButton": "Stop response",
  "comprehensiveDisclaimer": `【IMPORTANT DISCLAIMER】

**1. AI-Generated Content**
Responses from this application are generated by AI and are not a substitute for medical, legal, mental health, or other professional advice. Information provided is for general reference only.

**2. Emergency Situations**
This app includes crisis detection features, but in case of emergency or risk of self-harm/suicide, please contact immediately:
• Japan: Emergency Services 119, Inochi no Denwa 0570-783-556
• United States: 911, 988 Suicide & Crisis Lifeline
• Other countries: Local emergency services

**3. Medical & Mental Health**
For serious mental health issues, depression, anxiety disorders, or other mental health problems, please consult qualified medical professionals. This app is not a substitute for professional treatment.

**4. Privacy & Data**
• Conversation history is stored locally in your browser only
• Message content is analyzed for crisis detection but personal information is not stored
• See our Privacy Policy for details

**5. Translation & Language**
While this app supports multiple languages, some translations are auto-generated and their accuracy cannot be guaranteed.

**6. Usage Restrictions**
• Users under 18 require parental consent
• Use for illegal activities or harm to others is prohibited

**7. Limitation of Liability**
Developers and operators are not responsible for direct or indirect damages arising from use of this app.

Please use this app responsibly and understand these limitations.`,
  "privacyPolicyLinkText": "Privacy Policy",
  "privacyPolicyModalTitle": "Privacy Policy",
  "privacyPolicyKeyPointsTitle": "Key Points",
  "privacyPolicyKeyPoint1": "Conversation history is stored only in your browser",
  "privacyPolicyKeyPoint2": "IP addresses and session cookies are used only temporarily for rate limiting",
  "privacyPolicyKeyPoint3": "Anonymous usage and error data may be sent to Vercel Analytics and Sentry (only if you accept functional cookies)",
  "privacyPolicyKeyPoint4": "You can delete your data and stop using the service at any time",
  "privacyPolicyManagementTitle": "Data Management",
  "privacyPolicyManagementBody": "To delete conversation history, use the in-app \"Clear Conversation\" button, or clear local storage and cookies from your browser settings.",
  "privacyPolicyLastUpdated": "Last Updated: September 2026",
  "termsOfServiceLinkText": "Terms of Service",
  "termsOfServiceModalTitle": "Terms of Service",
  "privacyPolicy": `【PRIVACY POLICY】

Last Updated: April 2026

**1. Information We Collect**

**1.1 Automatically Collected Information**
• Browser language settings
• General location information (country code)
• Basic technical information (browser type, OS)
• IP address (processed temporarily for rate limiting and abuse prevention)
• HMAC-signed session cookie (\`sid\`): an anonymous server-issued identifier used for rate limiting

**1.2 User-Provided Information**
• Chat conversation content
• Voice input data (temporary processing only)

**1.3 Crisis Detection Analysis**
• Messages are automatically analyzed to detect crisis-related content for safety
• This analysis is solely for safety improvement and not for identification or other purposes

**2. How We Use Information**

**2.1 Service Provision**
• AI chatbot conversation functionality
• Multi-language support and translation
• Voice input features

**2.2 Safety Assurance**
• Detection of crisis situations and provision of appropriate resources
• Protection of user safety and welfare
• Rate limiting and prevention of abusive or malicious requests

**2.3 Service Improvement**
• Anonymized statistical analysis for feature enhancement
• Error detection and quality improvement

**3. Data Storage and Processing**

**3.1 Local Storage**
• Conversation history is stored only in your browser (local storage)
• Conversation content is not stored on our servers

**3.2 Temporary Processing**
• AI conversations are sent to Google Gemini API for processing
• Voice recognition is processed within the browser, voice data is not stored
• Crisis detection analysis is performed temporarily, only results are processed
• IP addresses and session cookies are used to evaluate rate limits and expire automatically after a short period (typically within 24 hours)

**3.3 Personal Information**
• We do not actively collect personally identifiable information (name, address, phone number)
• However, if you include personal information in your chat messages, that content will be sent to the AI service provider

**4. Information Sharing with Third Parties**

**4.1 AI Service Providers**
• Google Gemini API: For chat and translation functionality
• Information sent: Conversation content, language settings
• Google's Privacy Policy applies

**4.2 Analytics and Monitoring**
• Vercel Analytics: Collects anonymized traffic metrics (page views, referrers). Uses no cookies and does not identify individuals. Enabled only with your cookie consent
• Sentry: Collects error logs and performance data, used solely for quality improvement. Enabled only with your cookie consent
• Infrastructure: Vercel (hosting) and Upstash Redis (temporary counters for rate limiting)

**4.3 Emergency Exceptions**
• Legitimate requests from law enforcement agencies
• Life-threatening emergencies where deemed necessary

**5. Data Protection**

**5.1 Technical Safeguards**
• HTTPS encryption for communication protection
• HMAC-signed session cookie with HttpOnly, Secure, and SameSite=Lax attributes
• Minimal information collection principle
• Regular security updates

**5.2 Access Restrictions**
• Only developers can access data
• Administrative access is minimally restricted

**6. Your Rights**

**6.1 Data Deletion**
• You can delete conversation history and local storage from browser settings
• Use the in-app "Clear Conversation" function
• Clearing cookies in your browser also removes the session cookie

**6.2 Service Discontinuation**
• You can stop using the service at any time
• No complex procedures required as no account registration is needed

**7. International Data Processing**

• This service is available internationally
• Data processing occurs primarily in the US and Japan
• We strive to comply with privacy laws in each country

**8. Minor Protection**

• Users under 18 require parental consent
• We do not intentionally collect information from children under 13

**9. Cookies and Tracking**

The cookies and similar technologies we use:
• **Essential cookies** (\`sid\`): a server-issued HMAC-signed session cookie used for rate limiting
• **Consent-based measurement**: Vercel Analytics traffic metrics and Sentry error monitoring; enabled only if you accept the in-app cookie consent banner, and you can withdraw that consent from the same banner at any time
• **Local storage**: used to persist conversation history, language preferences, and cookie consent state
• We do not use advertising tracking cookies
• You can disable or delete cookies through your browser settings

**10. Policy Changes**

• Important changes will be notified within the app
• Continued use constitutes agreement to changes

**11. Contact**

For privacy-related questions or concerns, please contact us through the Issues section of our GitHub repository.

This Privacy Policy is created with user safety and privacy as our top priority.`,
  "termsOfService": `【TERMS OF SERVICE】

Last Updated: January 2025

**1. Service Overview**

This application "Sage's Love (AI)" (hereinafter "this Service") is a spiritual and life consultation service utilizing AI technology. Users can consult with an AI modeled on the wisdom of sages about life concerns and spiritual problems through dialogue.

**2. Terms of Use**

**2.1 Age Restrictions**
• Users under 18 require parental consent
• Users under 13 are not permitted to use this service

**2.2 Intended Use**
• This service is intended solely for spiritual, life consultation, and religious exploration purposes
• Cannot be used as a substitute for professional medical, legal, or mental health advice

**3. Prohibited Activities**

The following activities are prohibited:
• Acts that violate laws or are related to criminal activities
• Harassment, threats, or defamation of others
• Posting obscene, violent, or discriminatory content
• Acts that interfere with the operation of this service
• Unauthorized use of the service through technical means
• Commercial advertising, promotion, or solicitation activities
• Unauthorized collection or use of personal information
• Misusing AI responses to deceive others

**4. Account and Usage Limitations**

**4.1 Usage Limitations**
• Certain usage limitations are in place to maintain service quality
• Service usage may be restricted without notice if inappropriate use is confirmed

**4.2 Data Storage**
• Conversation history is stored locally in the browser and managed by users themselves
• Operators do not store or record users' conversation content

**5. AI Service Characteristics and Limitations**

**5.1 AI-Generated Content**
• Responses from this service are generated by AI and are not advice from actual sages
• AI responses may contain errors or inappropriate content
• We do not guarantee the accuracy or appropriateness of generated content

**5.2 Not a Substitute for Professional Advice**
• Cannot be used as a substitute for professional medical, legal, or mental health advice
• For serious problems, please consult appropriate professionals

**6. Intellectual Property Rights**

• Intellectual property rights related to the design, content, and system of this service belong to the operators
• Rights to content input by users belong to the users
• AI-generated content may be freely used for personal, non-commercial purposes only

**7. Privacy and Data Protection**

• User privacy protection is governed by the separately defined "Privacy Policy"
• Conversation content may be automatically analyzed by crisis detection functions to ensure safety

**8. Service Changes, Interruptions, and Termination**

• Operators may change, temporarily interrupt, or terminate service content without prior notice
• Service may be unavailable due to system maintenance, technical problems, or other unavoidable circumstances

**9. Disclaimer**

**9.1 Limitation of Operator Liability**
• Operators are not liable for direct or indirect damages arising from the use of this service, except in cases of intentional or gross negligence
• Not liable for damages arising from system failures, communication failures, third-party actions, etc.

**9.2 Third-Party Services**
• This service uses Google Gemini API, and Google's terms of service also apply
• For issues related to third-party services, please contact the respective service providers

**10. Changes to Terms**

• These terms of service may be changed without prior notice due to legal changes or service content changes
• Continued use after changes constitutes agreement to the changed content
• Important changes will be appropriately notified within the app

**11. Governing Law and Jurisdiction**

• These terms of service are governed by and interpreted under Japanese law
• For disputes related to this service, the court with jurisdiction over the operator's head office location shall be the exclusive agreed jurisdiction court

**12. Contact**

For questions or concerns about these terms of service, please contact us through the Issues section of our GitHub repository.

**13. Effectiveness**

These terms of service take effect when users use this service.`,
  "disclaimerLinkText": "Disclaimer",
  "disclaimerModalTitle": "Disclaimer",
  "closeModalButton": "Close",
  "cancelButton": "Cancel",
  "helpButtonTooltip": "How to Use",
  "helpModalTitle": "How to Use This App",
  "helpItemHistory": "Conversations are automatically saved in your browser. You can reset a conversation using the trash icon in the top right.",
  "helpItemControls": "You can freely change the language and text size using the buttons in the header.",
  "helpItemShare": "With the share button, you can easily copy or share a link to this app.",
  "confirmClearTitle": "Reset conversation?",
  "confirmClearText": "The entire current conversation history will be deleted and you will return to the initial state. This action cannot be undone.",
  "confirmClearButton": "Reset",
  "sageIsResponding": "The Sage is preparing a response",
  "errorPrefix": "Error",
  "errorMessageDefault": "An unexpected error occurred.",
  "errorSageResponsePrefix": "My apologies, an error occurred: ",
  "errorNoApiKeyConfig": "I am sorry, but the necessary information to connect to the service is not configured. Please contact the administrator. (ERR_NO_API_KEY_CONFIG)",
  "errorNoApiClient": "I am sorry, but the service is currently being configured. Please try again later. (ERR_NO_API_CLIENT)",
  "errorAuth": "It seems there is an issue connecting to the service. Please try again later. (AUTH_ERR)",
  "errorQuota": "It appears many are seeking wisdom at this moment. Please try again after a short while. (QUOTA_ERR)",
  "errorModel": "There might be an issue with the internal settings of the service. It would be helpful if you could inform the administrator. (MODEL_ERR)",
  "errorGeneric": "A problem arose while weaving words of wisdom. Please try again later. (GEN_ERR)",
  "errorRateLimit": "Access is temporarily concentrated. Please wait a little while and try again.",
  "errorBurstLimit": "You seem to be in a bit of a hurry. Take a breath, and ask again slowly.",
  "errorSessionLimit": "You have reached today's usage limit. Please try again tomorrow.",
  "errorContentSafety": "There seems to be an issue with the content of your message. Please try different words.",
  "errorNetwork": "There seems to be a problem with the network connection. Please check your internet connection.",
  "errorTimeout": "The connection took too long. Please wait a moment and try again.",
  "errorServiceUnavailable": "The service is temporarily unavailable. Please try again in a little while.",
  "errorDailyCostLimit": "Today's usage limit has been reached. Please visit again tomorrow.",
  "errorHourlyCostLimit": "The hourly usage limit has been reached. Please try again after a while.",
  "errorEmergencyCostLimit": "The service is temporarily restricted. Please try again later.",
  "MESSAGE_TOO_LONG": "Your message is a little too long. Please keep it within 1,000 characters and try again.",
  "HISTORY_TOO_LONG": "This conversation has grown long. Please save anything important, use “Clear conversation,” and then continue.",
  "languageSelectorLabel": "Select language",
  "textSizeLabel": "Text Size",
  "textSizeNormal": "Normal",
  "textSizeLarge": "Large",
  "textSizeNormalAria": "Set text size to normal",
  "textSizeLargeAria": "Set text size to large",
  "textSizeXLarge": "X-Large",
  "textSizeXLargeAria": "Set text size to extra large",
  "copyMessageButtonLabel": "Copy message",
  "messageCopiedTooltip": "Copied!",
  "clearConversationButtonLabel": "Clear conversation",
  "clearConversationTooltip": "Clear the current conversation and start a new one",
  "shareAppButtonLabel": "Share",
  "shareAppTooltip": "Share this app",
  "shareSuccessTooltip": "Link copied to clipboard!",
  "shareWithLine": "Share with LINE",
  "shareWithTwitter": "Share with X",
  "shareWithFacebook": "Share with Facebook",
  "copyLink": "Copy link",
  "promptSuggestionsTitle": "Need inspiration? Try asking:",
  "promptSuggestion1": "How can I find inner peace?",
  "promptSuggestion2": "What is the meaning of life?",
  "promptSuggestion3": "How to deal with difficult emotions?",
  "promptSuggestion4": "What is my true self?",
  "cookieBannerTitle": "Cookie Usage",
  "cookieBannerDescription": "This site uses cookies to improve our services and for analysis purposes. In accordance with GDPR regulations, we use them with your consent.",
  "cookieBannerCustomize": "Customize settings",
  "cookieBannerAcceptAll": "Accept all",
  "cookieBannerRejectAll": "Reject all",
  "cookiePreferencesTitle": "Cookie Settings",
  "cookieNecessaryTitle": "Necessary Cookies",
  "cookieNecessaryDescription": "These cookies are required for the basic functionality of the site. They cannot be disabled.",
  "cookieFunctionalTitle": "Functional Cookies",
  "cookieFunctionalDescription": "Used to improve app functionality (language settings, theme settings, anonymous usage analytics, etc.).",
  "cookieAlwaysActive": "Always active",
  "cookieSavePreferences": "Save preferences",
  "cookieSettingsLinkText": "Cookie settings",
  "closeButton": "Close",
  "errorBoundary": {
    "genericError": "An unexpected error occurred",
    "chunkLoadError": "Application failed to load",
    "memoryError": "Memory shortage occurred",
    "networkError": "Network error occurred",
    "genericDescription": "We apologize, but an unexpected problem has occurred. This may be a temporary issue.",
    "chunkLoadDescription": "Part of the application could not load properly. Please reload the page.",
    "memoryDescription": "Your browser is running out of memory. Please close other tabs and try again.",
    "networkDescription": "There is a problem with your network connection. Please check your connection.",
    "retryButton": "Retry",
    "reloadButton": "Reload Page",
    "reportButton": "Report Issue",
    "reportingButton": "Reporting...",
    "showDetails": "Show Details",
    "errorMessage": "Error Message",
    "errorType": "Error Type",
    "stackTrace": "Stack Trace",
    "componentStack": "Component Stack",
    "retryInfo": "Retry {{current}}/{{max}} times",
    "feedbackText": "If the problem persists, please feel free to let us know:",
    "feedbackLink": "Report an Issue"
  },
  "seoTitle": "Spiritual Guidance with a Sage's Wisdom - Free AI Counseling",
  "seoHeading1": "聖者の愛（AI）とは",
  "seoDescription1": "Sage's Love (AI) is an innovative spiritual guidance service that blends ancient wisdom with modern AI technology. Receive deep, sage-like insight into life's worries and matters of the heart, anytime, 24/7.",
  "seoHeading2": "このサービスの特徴",
  "seoDescription2": "完全無料でご利用いただけるこのサービスは、宗教的な垣根を越えて、すべての人に開かれた心のsanctuary（聖域）です。プライバシーを完全に保護しながら、深遠な智慧と温かい愛に満ちた助言を提供します。",
  "seoHeading3": "主な機能",
  "seoFeature1": "24時間365日利用可能 - いつでもあなたの心に寄り添います",
  "seoFeature2": "多言語対応 - 日本語、英語、スペイン語、ポルトガル語で相談可能",
  "seoFeature3": "完全無料 - 登録不要、費用も一切かかりません",
  "seoFeature4": "プライバシー保護 - 個人情報の収集や保存は一切行いません",
  "seoFeature5": "危機検出機能 - 緊急時には適切なサポートリソースを提供",
  "seoHeading4": "どのような相談ができるか",
  "seoDescription3": "人生の意味や目的、人間関係の悩み、スピリチュアルな疑問、日常の心配事まで、あらゆる心の問題について相談できます。聖者のような深い洞察と慈愛に満ちた助言で、あなたの心の平安を取り戻すお手伝いをいたします。",
  "seoHeading5": "安全性とプライバシー",
  "seoDescription4": "すべての会話はお使いのブラウザ内にのみ保存され、外部に送信されることはありません。また、緊急時の安全確保のため、危機的な内容を自動検出し、適切なサポートリソースを提供する機能を備えています。",
  // Error Boundary translations
  "errorBoundaryTitle": "An Unexpected Error Occurred",
  "errorBoundaryMessage": "We apologize for the inconvenience. An error has occurred in the application.",
  "errorBoundaryDetailsToggle": "Show technical details",
  "errorBoundaryResetButton": "Try Again",
  "errorBoundaryReloadButton": "Reload Page",
  "errorBoundaryHelpText": "If the problem persists, please try clearing your browser cache."
};